### ISSUE TITLE
mPDF export temporary files location

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks#135]
Hi @bdolor, noticed (this escaped me on my initial testing) that the mPDF routine uses three directories within `/symbionts` as temporary directories for export. I wrapped the error message hook in a conditional block to keep it from showing up on pressbooks.com (see https://github.com/pressbooks/pressbooks/commit/9c88bfa2103f1a3ed66f9693aa894e3802d02bb4) but I'd much prefer if you could restrict temporary file storage to the book's uploads directory (`/wp-content/uploads/site/2/etc`). Is this possible? If non-trivial I'd be happy to assist in any way that I can. Thanks!

**Comment by bdolor** [comment]
Hi @greatislander — This is possible only by modifying code within the mpdf class, which runs the risk of divorcing ourselves from future updates of mpdf. That these directories need to be be writeable was problematic for me as well since it can only be solved if you have root/sudo access to the server. 

However, under most circumstances the plugins are being pulled in from the wordpress plugin repo, where apache is the owner of the directory so it may be an issue only if people are pulling in from github using git under another user other than apache. Nevertheless, I think it's potentially a problem that could be solved better than just giving people a warning. 

The obvious thing would be to commit the directories with different/writeable file permissions — change to 775 and hope that apache is part of the group? 

Thoughts?

examples of baked in directory paths: 
- https://github.com/pressbooks/pressbooks/blob/dev/symbionts/mpdf/graph.php#L13
- https://github.com/pressbooks/pressbooks/blob/dev/symbionts/mpdf/includes/out.php#L3

**Comment by hughmcguire** [comment]
@greatislander these error messages are showing up in all client installs (just confirmed they *are* in all of them). 

need to address those error messages at least, in whatever way is best for you.

**Comment by greatislander** [comment]
Fixed now, @hughmcguire.

**Comment by hughmcguire** [comment]
@greatislander ... another one with these errors showing, this one on pressbooks.com see: 
http://inocenciafacil.pressbooks.com/wp-admin/admin.php?page=pressbooks

@cmurtagh restarted memecache, my goto for "hrm, weird, will this fix it" ... but it did not fix it.

**Comment by hughmcguire** [comment]
@greatislander pressbooks.com users getting these error messages still. please remove this feature until this error message issue is resolved.

**Comment by greatislander** [comment]
@hughmcguire The error message has been resolved.

**Comment by hughmcguire** [comment]
thanks!
